#!/bin/bash
set -euo pipefail
HERE="$(dirname "$0")"
term="$(sed -r 's/\.fm$//' <<< "$1")"
fm="$(sed -r 's/[.0-9]*$//' <<< "$term").fm"
tmp="log/fm.$(date -Ins | tr ':,' '-.')"

cd "$HERE"
mkdir -p "$tmp"
touch "$tmp/log"

# No need to download duplicates.
cp "$fm" "$tmp"
ln -sf "$PWD/.fmc" "$tmp"
cd "$tmp"

show() {
  cmd="$@"
  echo -e "\n$ $cmd"
  eval "$cmd"
}

show cat "$fm"

{
  show fm "$fm"
  show "seq 10 | fmio $term"
} | tee log

echo
echo '###'
echo "# Saved to $tmp/log"
