#!/bin/bash
# Remove duplicates.

uniq-v() {
  # An inverse for uniq(1): Print only non-unique lines.
  set -x
  uniq --all-repeated=prepend "$@" |
    sed '/^$/ {N; d}'
}

ls -d log/fm.*/ |
  sed 's/$/log/' |
  xargs -r touch

md5sum log/fm.*/log |
  sort |
  uniq-v -w32 |
  col 2 |
  xargs -r dirname |
  xargs -r echo rm -r \
;
