#!/usr/bin/env python3
"""A "fizzbuzz" program.

    $ seq 15 20 | ./fizzbuzz
    15 fizzbuzz
    18 fizz
    20 buzz
"""

FIZZ = 3
BUZZ = 5


def fizzbuzz(numbers):
    """Fizz. Buzz."""
    for number in numbers:
        output = []
        if number % FIZZ == 0:
            output.append('fizz')
        if number % BUZZ == 0:
            output.append('buzz')

        if output:
            print(number, ''.join(output))


def normalize_lines(lines):
    """Remove blank and commented lines. Remove leading/trailing whitespace."""
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        yield line


def lines_to_numbers(lines):
    for line in lines:
        # throws ValueError on non-integer input
        yield int(line)


def pipe(input, *functions):
    result = input
    for function in functions:
        result = function(result)
    return result


def main():
    from sys import stdin

    return pipe(
        stdin,
        normalize_lines,
        lines_to_numbers,
        fizzbuzz,
    )


if __name__ == '__main__':
    exit(main())
